### PR TITLE
Feature/cctv player detection

### PR DESCRIPTION
**Pull request by MJ-Lenomta**
# Description:
CCTV works like an AI vision.  

### How it works:
Increases the  player's stealth meter on suspect and overt state of the camera. Camera can be destroyed by calling function OnCameraDestroyed.

## Guidelines:
- [x] I have consulted my lead when making this request
- [x] I have followed merging practices
- [x] I have assigned the proper target branch this will merge to

### Features added:
- CCTV player detection

### Features removed:
- None

### Potential Affected branches:
- %{target_branch}
- None

### Potential Affected features:
- None

## Leads Only
- [ ] This merge request has been approved by all the leads in my department

### CODE REVIEW

**Review by LauSnchzz — APPROVED** [review]
Since noise mechanic was already merged here and there was little to no changes in major files after the merge. This seems fine to approve.

**Review by DavidGutierrez-Benilde — APPROVED** [review]

**Review by AlexanderGregorSanchez — APPROVED** [review]
i dont know man maybe

**Comment by LauSnchzz** [comment]
Changes looks good and gave tested in a local merge. All three scenes (Noise Mechanic, CCTV, Stealth) seems to be working as intended. Good job!

**Comment by LauSnchzz** [comment]
DO NOT DELETE THIS BRANCH! I WILL DELETE THIS BRANCH ONCE NO PROBLEMS ARISE

**Pull request merged**
